export const questions = [
    'how to trade',
    'how to open buy order widget',
    'how to open sell order widget',
    'how to view portfolio',
    'how to check stock prices',
    'how to access market news',
    'how to read analyst ratings',
    'how to request margin financing',
    'how to switch to global trading',
    'how to view trading history',
    'how to set price alerts',
    'how to enable notifications',
    'how to customize dashboard',
    'how to view watchlist',
    'how to add stock to watchlist',
    'how to remove stock from watchlist',
    'how to access promotions',
    'how to view trading fees',
    'how to apply for a trading account',
    'how to verify account',
    'how to reset password',
    'how to contact support',
    'how to update personal information',
    'how to deposit funds',
    'how to withdraw funds',
    'how to transfer funds between accounts',
    'how to set up automatic investments',
    'how to view transaction history',
    'how to download statements',
    'how to manage investment preferences',
    'how to find investment ideas',
    'how to open options trading widget',
    'how to trade options',
    'how to open futures trading widget',
    'how to trade futures',
    'how to set stop loss',
    'how to set take profit',
    'how to view market trends',
    'how to view company financials',
    'how to read stock charts',
    'how to use technical indicators',
    'how to view dividend information',
    'how to participate in IPOs',
    'how to access research reports',
    'how to join trading community',
    'how to follow other traders',
    'how to share trading ideas',
    'how to get trading recommendations',
    'how to use trading simulator',
    'how to open demo account',
    'how to access educational resources',
    'how to watch trading webinars',
    'how to read trading blogs',
    'how to listen to market podcasts',
    'how to set investment goals',
    'how to manage risk',
    'how to diversify portfolio',
    'how to rebalance portfolio',
    'how to use portfolio analysis tools',
    'how to calculate returns',
    'how to optimize tax strategies',
    'how to find sustainable investments',
    'how to invest in ETFs',
    'how to invest in mutual funds',
    'how to invest in bonds',
    'how to invest in commodities',
    'how to invest in real estate',
    'how to use margin account',
    'how to calculate margin requirements',
    'how to avoid margin calls',
    'how to apply for loans',
    'how to view credit information',
    'how to improve credit score',
    'how to view spending analysis',
    'how to create a budget',
    'how to track expenses',
    'how to set savings goals',
    'how to invest for retirement',
    'how to open retirement account',
    'how to transfer retirement funds',
    'how to manage retirement portfolio',
    'how to calculate retirement needs',
    'how to invest for college',
    'how to open college savings account',
    'how to transfer college savings',
    'how to manage college savings portfolio',
    'how to calculate college savings needs',
    'how to access tax documents',
    'how to file taxes',
    'how to understand tax forms',
    'how to use tax calculator',
    'how to plan for taxes',
    'how to get tax advice',
    'how to avoid tax penalties',
    'how to report investment income',
    'how to handle investment losses',
    'how to use tax-loss harvesting',
    'how to access financial planning tools',
    'how to get financial advice',
    'how to create a financial plan'
]